CREATE TABLE BookTag
(
	[BookId] UNIQUEIDENTIFIER NOT NULL,
	[TagId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_TagGenre] PRIMARY KEY ([BookId], [TagId]),
	CONSTRAINT [FK_BookTag_Book] FOREIGN KEY ([BookId]) REFERENCES [Books] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_BookTag_Tag] FOREIGN KEY ([TagId]) REFERENCES [Tags] ([Id]) ON DELETE CASCADE
);