CREATE TABLE [Users]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newId(),

	[Password] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,

	[UserName] NVARCHAR(50) NOT NULL, 
    [DateJoined] DATETIME2 NOT NULL DEFAULT GetDate(), 
    [Bio] NVARCHAR(MAX) NULL, 
    [Image] NVARCHAR(MAX) NULL,
    [IsActive] BIT NOT NULL DEFAULT 1
);